// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeClientInProjectModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeClientInProjectModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201909120940552_removeClientInProjectModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
